name: Dummy

on: push

jobs:
    validate-notebooks:
      name: Validate Notebooks
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup Conda Environment
          uses: conda-incubator/setup-miniconda@v2
          with:
            activate-environment: uc-python
            environment-file: environment.yml
        - name: Diagnose
          shell: bash -l {0}
          run: |
            conda info
            conda list
